all:
  hosts:
    web:
      ansible_host: "{{ lookup('env', 'EC2_HOST') }}"
      ansible_user: "{{ lookup('env', 'EC2_USER') }}"
      ansible_ssh_private_key_file: ~/.ssh/practice-key
      ansible_python_interpreter: /usr/bin/python3